version: '3'
# TODO : use local env file for env variables
services:
  # PostgreSQL service
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ChangeMe
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports: 
      - 5433:5432
    networks:
      - app-network

  # mailer:
  #   image: schickling/mailcatcher
  #   ports: 
  #     - "1025:1025"
  #     - "1080:1080"
  #   networks:
  #     - app-network

volumes:
  database_data:

networks:
  app-network:



