version: '3'
services:
  database:
    container_name: greencare_db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports: 
      - 5433:5432
    networks:
      - app-network

  database_test:
    container_name: greencare_db_test
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_TEST_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database_test_data:/var/lib/postgresql/data:rw
    ports: 
      - 5434:5432
    networks:
      - app-network

volumes:
  database_data:
  database_test_data:

networks:
  app-network:
