name: CI - PHP QA

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    container: jakzal/phpqa:php8.2

    steps:
      - uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

  security_checker:
    needs: install_dependencies
    runs-on: ubuntu-latest
    container: jakzal/phpqa:php8.2

    steps:
      - uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Check Security
        run: local-php-security-checker composer.lock

  php_coding_standard:
    needs: install_dependencies
    runs-on: ubuntu-latest
    container: jakzal/phpqa:php8.2

    steps:
      - uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Check Coding Standards
        run: |
          php-cs-fixer fix ./src --dry-run --rules=@Symfony --verbose
          phpstan analyse ./src -l3
          phpdd ./src
          phpcpd ./src --exclude './src/Controller/Admin/' --exclude './src/Entity'

  php_lint:
    needs: install_dependencies
    runs-on: ubuntu-latest
    container: jakzal/phpqa:php8.2

    steps:
      - uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Lint code
        run: |
          chmod +x ./bin/console
          ./bin/console lint:twig templates --env=prod
          ./bin/console lint:yaml config --parse-tags
          ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
